apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-lanre-data-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 5Gi
---
kind: Secret
apiVersion: v1
metadata:
  name: mssql-lanre-secret
  namespace: lanrens
data:
  SA_PASSWORD: UGxhaW4yMDE4IQ==
  CONNECTION_STRING_LANRE: U2VydmVyPW1zc3FsLWxhbnJlLXNlcnZpY2UsMTQzMztEYXRhYmFzZT1MYW5yZS5MYW5yZURiO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9UGxhaW4yMDE4IQ==
type: Opaque