apiVersion: v1
kind: Service
metadata:
  name: mssql-lanre-service
spec:
  selector:
    app: mssql-lanre
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mssql-lanre-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql-lanre
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: microsoft/mssql-server-linux
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        # - name: SA_PASSWORD
        #   value: "Plain2018!"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-lanre-secret
              key: SA_PASSWORD
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-lanre-data-claim