apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: lanre-host
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: lanre
    spec:
      containers:
        - image: "ericuss/lanreclientshost:latest"
          imagePullPolicy: Always
          name: lanre-host
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "https://+:443;http://+:80"
          - name: ASPNETCORE_HTTPS_PORT
            value: "443"
          - name: HttpsConfig__Port
            value: "443"
          - name: ConnectionStrings__Lanre
            value: "Server=lanre-sql-data;Initial Catalog=Lanre.LanreDb;Persist Security Info=False;User ID=sa;Password=Pass@word;MultipleActiveResultSets=False;Encrypt=false;TrustServerCertificate=False;Connection Timeout=30;"